module.exports = {
  headerContainer: {
    fontFamily: "'Poiret One', cursive",
    height: "86px",
  },
  navigation: {
    backgroundColor: "white",
    color: "#3b3a36",
    display: "inline-block",
    width: "100%",
    height:"86px",
    position: "fixed",
    zIndex: "1",
    borderBottom: "1px solid #ccc",
  },
  navigationMobile: {
    backgroundColor: "white",
    color: "#3b3a36",
    display: "inline-block",
    width: "100%",
    height:"86px",
    borderBottom: "1px solid #ccc",
  },
  logo: {
    height: "80px",
    float: "left",
    paddingLeft: "10px",
    paddingTop: "5px",
    paddingRight: "5px"
  },
  noSpace: {
    padding: "0",
    margin: "0",
  },
  menuContainer: {
    position: "absolute",
    top: "0",
    right: "0",
  },
  noSpaceFloat: {
    padding: "0",
    margin: "0",
    float: "right",
  },
  title: {
    textDecoration: "none",
    color: "#3b3a36",
    fontWeight: "700",
    display: "inline-block",
    cursor: "pointer",
    fontSize: "32px",
  },
  titleMobile: {
    textDecoration: "none",
    color: "#3b3a36",
    fontWeight: "700",
    display: "inline-block",
    cursor: "pointer",
    fontSize: "32px",
    lineHeight:"normal",
  },
  menu: {
    float: "left",
    margin: "0",
    padding: "0",
  },
  menuMobile: {
    float: "right",
    width: "100%",
    margin: "0",
    padding: "0",
  },
  subMenu: {
    display: "none",
    margin: "0",
    padding: "0",
    width: "100%",
    display: "none",
    zIndex: "2",
    position: "absolute",
    top: "86px",
    right: "0",
    backgroundColor: "transparent",
    maxWidth: "100%",
  },
  menuItem: {
    color: "#45415E",
    height:"86px",
    listStyle: "none",
    padding: "25px 45px",
    fontSize: "24px",
    cursor: "pointer",
    display: "inline-block",
  },
  menuItemHover: {
    backgroundColor:"rgba(216, 216, 216, 0.6)",
    color: "#524D70",
    height:"86px",
    listStyle: "none",
    padding: "25px 45px",
    fontSize: "24px",
    cursor: "pointer",
    display: "inline-block",
  },
  menuSubItem: {
    backgroundColor:"#f4f4f4",
    color: "#222",
    height:"65px",
    listStyle: "none",
    padding: "18px 20px",
    fontSize: "18px",
    cursor: "pointer",
  },
  menuSubItemHover: {
    backgroundColor:"#ccc",
    color: "#222",
    height:"65px",
    listStyle: "none",
    padding: "18px 20px",
    fontSize: "18px",
    cursor: "pointer",
  },
  menuNavButton: {
    color: "#f4f4f4",
    height:"86px",
    width:"86px",
    listStyle: "none",
    padding: "20px",
    fontSize: "24px",
    cursor: "pointer",
    display: "inline-block",
  },
  menuNavButtonHover: {
    backgroundColor:"rgba(216, 216, 216, 0.6)",
    color: "#f4f4f4",
    height:"86px",
    width:"86px",
    listStyle: "none",
    padding: "20px",
    fontSize: "24px",
    cursor: "pointer",
    display: "inline-block",
  }
}
