module.exports = {
  headerContainer: {
    fontFamily: "'Lucida Sans Unicode', 'Lucida Grande', sans-serif",
    height: "44px",
  },
  navigation: {
    backgroundColor:"rgba(255,255,255,0.9)",
    color: "#222",
    width: "100%",
    height:"44px",
    position: "fixed",
    zIndex: "9",
    borderBottom: "1px solid #ccc",
  },
  navigationMobile: {
    backgroundColor:"rgba(255,255,255,0.9)",
    color: "#222",
    height:"44px",
    borderBottom: "1px solid #ccc",
  },
  logo: {
    height: "38px",
    display:"block",
    margin:"3px 0px",
  },
  noSpace: {
    padding: "0",
    margin: "0",
  },
  menuContainer: {
    float:"right",
    height:"44px",
  },
  noSpaceFloat: {
    padding: "0",
    margin: "0",
    float: "right",
  },
  title: {
    textDecoration: "none",
    color: "#222",
    display: "inline-block",
    cursor: "pointer",
    fontSize: "22px",
  },
  titleMobile: {
    textDecoration: "none",
    color: "#222",
    display: "inline-block",
    cursor: "pointer",
    fontSize: "22px",
  },
  menu: {
    float: "left",
    margin: "0",
    padding: "0",
  },
  menuMobile: {
    float: "right",
    width: "100%",
    margin: "0",
    padding: "0",
  },
  subMenu: {
    display: "none",
    margin: "0",
    padding: "0",
    width: "100%",
    display: "none",
    zIndex: "9",
    position: "absolute",
    top: "44px",
    right: "0",
    backgroundColor: "transparent",
    maxWidth: "100%",
  },
  menuItem: {
    color: "#222",
    height:"44px",
    lineHeight:"44px",
    listStyle: "none",
    margin:"0",
    padding: "0px 25px",
    fontSize: "18px",
    cursor: "pointer",
    display: "inline-block",
  },
  menuItemHover: {
    color: "#666",
    height:"44px",
    lineHeight:"44px",
    listStyle: "none",
    margin:"0",
    padding: "0px 25px",
    fontSize: "18px",
    cursor: "pointer",
    display: "inline-block",
  },
  menuItemFarRight: {
    color: "#222",
    height:"44px",
    lineHeight:"44px",
    listStyle: "none",
    margin:"0",
    padding: "0px 0px 0px 25px",
    fontSize: "18px",
    cursor: "pointer",
    display: "inline-block",
  },
  menuItemFarRightHover: {
    color: "#666",
    height:"44px",
    lineHeight:"44px",
    listStyle: "none",
    margin:"0",
    padding: "0px 0px 0px 25px",
    fontSize: "18px",
    cursor: "pointer",
    display: "inline-block",
  },
  menuItemButton: {
    color: "#fff",
    height: "28px",
    border: "2px solid #07c",
    borderRadius: "4px",
    backgroundColor: "#0070c9",
    background: "-webkit-linear-gradient(#42a1ec, #0070c9)",
    background: "linear-gradient(#42a1ec, #0070c9)",
    fontSize: "18px",
    padding: "0px 24px",
    margin: "6px 0px 6px 15px",
    cursor: "pointer",
    lineHeight: "24px",
    display: "inline-block",
  },
  menuItemButtonHover: {
    color: "#fff",
    height: "28px",
    border: "2px solid #07c",
    borderRadius: "4px",
    backgroundColor: "#147bcd",
    background: "-webkit-linear-gradient(#51a9ee, #147bcd)",
    background: "linear-gradient(#51a9ee, #147bcd)",
    fontSize: "18px",
    padding: "0px 24px",
    margin: "6px 0px 6px 15px",
    cursor: "pointer",
    lineHeight: "24px",
    display: "inline-block",
  },
  menuSubItem: {
    backgroundColor:"#444",
    color: "#fff",
    height:"65px",
    listStyle: "none",
    padding: "18px 20px",
    fontSize: "18px",
    cursor: "pointer",
  },
  menuNavButton: {
    color: "#f4f4f4",
    height:"44px",
    width:"44px",
    listStyle: "none",
    padding: "10px",
    fontSize: "24px",
    cursor: "pointer",
    display: "inline-block",
  },
  menuNavButtonHover: {
    backgroundColor:"rgba(216, 216, 216, 0.6)",
    color: "#f4f4f4",
    height:"44px",
    width:"44px",
    listStyle: "none",
    padding: "10px",
    fontSize: "24px",
    cursor: "pointer",
    display: "inline-block",
  }
}
