module.exports = [{
  isActive: true,
  name: "Zachary Allen",
  title: "CEO and CTO",
  type: "team",
  img: "/img/zach",
  description: "Zach founded Slate Robotics in August 2018 with the mission to make general purpose robots more affordable. He continues to oversee the company's product strategy -- including the design, engineering and manufacturing of these robots. Zach has been fascinated by personal robots for years. He designed and built the ground-breaking TR1 in his garage over the course of a year after trying to find an affordable robot development platform. Zach's background is in Software Engineering. He worked as a developer for 3 years after graduating from Drury University with a BA in Spanish.",
  linkedin: "https://www.linkedin.com/in/zachary-allen-674ab8a9/",
  twitter: "https://twitter.com/ZachAllen417",
  facebook: "https://www.facebook.com/zach.allen.566",
},{
  isActive: true,
  name: "COO",
  name: "Dylan Hall",
  title: "COO",
  type: "team",
  img: "/img/dylan",
  description: "Dylan joined Slate Robotics in April 2018 to handle operations. He oversees and implements processes required of manufacturing, production, supply-chain, and business infrastructure. Dylan has a background in computer networking and working like an absolute animal. He's dependable and determined to make every single customer of Slate Robotics delighted with their robot.",
},{
  isActive: false,
  name: "CTO",
  title: "Chief Technology Officer",
  type: "team",
  img: "/img/person-icon",
  description: "",
},{
  isActive: true,
  name: "Brian Allen",
  title: "Investor & Board Member",
  type: "investor",
  img: "/img/brian",
  description: "Brian is the founder of Pension Consultants, Inc., and he has served as President and Board Chairperson since its inception in 1994. He serves as Chairperson for Pension Consultants’ Investment Committee, which oversees nearly $3.1B in AUM/AUA. He was approached by Zach in May 2017 to help fund the early stages of Slate Robotics, and he has been an unwaivering proponent of the vision of the company and of the company itself.",
  linkedin: "https://www.linkedin.com/in/brianallenretireadviser1/",
  twitter: "https://twitter.com/RetireAdviser1",
}];
