module.exports = {
  container: {
    color: "#3b3a36",
    minHeight: "calc(100% - 86px)",
    fontFamily: "'Lucida Sans Unicode', 'Lucida Grande', sans-serif",
    textAlign: "center",
    fontSize: "16px",
    backgroundColor:"#fff",
  },
  menu: {
    fontSize:"20px",
    position:"fixed",
    left:"0px",
    zIndex:"1",
    width:"100%",
    backgroundColor:"rgba(255,255,255,0.8)",
    height:"34px",
    borderBottom:"1px solid #ccc",
    margin:"0 auto",
  },
  menuMobile: {
    fontSize:"20px",
    position:"absolute",
    top:"44px",
    left:"0px",
    zIndex:"1",
    width:"100%",
    backgroundColor:"rgba(255,255,255,0.8)",
    height:"34px",
    borderBottom:"1px solid #ccc",
    margin:"0 auto",
  },
  buttonContainer: {
    fontSize:"24px",
    marginTop:"20px",
    marginBottom:"40px"
  },
  menuButton: {
    color: "#fff",
    height: "28px",
    border: "2px solid #07c",
    borderRadius: "4px",
    backgroundColor: "#0070c9",
    background: "-webkit-linear-gradient(#42a1ec, #0070c9)",
    background: "linear-gradient(#42a1ec, #0070c9)",
    fontSize: "18px",
    padding: "0px 24px",
    cursor: "pointer",
    lineHeight: "24px",
    display: "inline-block",
  },
  menuButtonHover: {
    color: "#fff",
    height: "28px",
    border: "2px solid #07c",
    borderRadius: "4px",
    backgroundColor: "#147bcd",
    background: "-webkit-linear-gradient(#51a9ee, #147bcd)",
    background: "linear-gradient(#51a9ee, #147bcd)",
    fontSize: "18px",
    padding: "0px 24px",
    cursor: "pointer",
    lineHeight: "24px",
    display: "inline-block",
  },
  text: {
    fontFamily: "'Rokkitt', serif",
  },
  img: {
    maxWidth: "100%",
  },
}
