module.exports = {
  container: {
    color: "#3b3a36",
    minHeight: "calc(100% - 86px)",
    fontFamily: "'Lucida Sans Unicode', 'Lucida Grande', sans-serif",
    textAlign: "center",
    fontSize: "16px",
    backgroundColor:"#fff",
  },
  menu: {
    fontSize:"20px",
    position:"fixed",
    left:"0px",
    zIndex:"9",
    width:"100%",
    backgroundColor:"rgba(255,255,255,0.8)",
    height:"34px",
    borderBottom:"1px solid #ccc",
    margin:"0 auto",
  },
  menuMobile: {
    fontSize:"20px",
    position:"absolute",
    top:"44px",
    left:"0px",
    zIndex:"9",
    width:"100%",
    backgroundColor:"rgba(255,255,255,0.8)",
    height:"34px",
    borderBottom:"1px solid #ccc",
    margin:"0 auto",
  },
  buttonContainer: {
    marginTop:"20px",
    marginBottom:"40px"
  },
  text: {
    fontFamily: "'Rokkitt', serif",
  },
  img: {
    maxWidth: "100%",
  },
  menuButton: {
    color: "#fff",
    height: "28px",
    border: "2px solid #07c",
    borderRadius: "4px",
    backgroundColor: "#0070c9",
    background: "-webkit-linear-gradient(#42a1ec, #0070c9)",
    background: "linear-gradient(#42a1ec, #0070c9)",
    fontSize: "14px",
    padding: "0px 24px",
    cursor: "pointer",
    lineHeight: "24px",
    display: "inline-block",
  },
  menuButtonHover: {
    color: "#fff",
    height: "28px",
    border: "2px solid #07c",
    borderRadius: "4px",
    backgroundColor: "#147bcd",
    background: "-webkit-linear-gradient(#51a9ee, #147bcd)",
    background: "linear-gradient(#51a9ee, #147bcd)",
    fontSize: "14px",
    padding: "0px 24px",
    cursor: "pointer",
    lineHeight: "24px",
    display: "inline-block",
  },
  iconDescriptionContainer: {
    padding:"10px 0px",
  },
  imageContainer: {
    overflow: "hidden",
    position: "relative",
    height: "100%",
  },
  imageCenter: {
    position: "absolute",
    right: "-9999px",
    left: "-9999px",
    margin: "auto",
  },
  detail1Container: {
    backgroundColor:"#222",
    color:"#fff",
    paddingBottom:"75px",
    paddingTop:"75px",
  },
  detail2Container: {
    backgroundColor:"#fff",
    color:"#222",
    paddingBottom:"75px",
    paddingTop:"75px",
  },
  detail3Container: {
    backgroundColor:"#f8f8f8",
    color:"#222",
    paddingBottom:"75px",
    paddingTop:"75px",
  },
  detail4Container: {
    backgroundColor:"#222",
    color:"#fff",
    paddingBottom:"75px",
    paddingTop:"75px",
  },
  detail5Container: {
    backgroundColor:"#222",
    color:"#fff",
    paddingBottom:"75px",
    paddingTop:"75px",
  },
  learnMoreContainer: {
    display:"none",
    position:"absolute",
    width:"100%",
    height:"100%",
    zIndex:"1",
    backgroundColor:"rgba(34,34,34,0.5)",
    color:"#fff",
  },
  learnMoreText: {
    textAlign:"left",
    padding:"15px",
  },
  learnMoreButtonContainer: {
    zIndex:"2",
    position:"absolute",
    height:"72px",
    bottom:"20px",
    left:"0",
    right:"0",
  },
  learnMoreButton: {
    display:"none",
    border:"3px solid #58546f",
    borderRadius:"50%",
    backgroundColor:"rgba(88, 84, 111, 0.9)",
    color:"#fff",
    fontSize:"44px",
    fontWeight:"900",
    width:"72px",
    height:"72px",
    margin:"10px auto",
    cursor:"pointer",
  }
}
